set_property IOSTANDARD LVCMOS33 [get_ports adau1761_cclk]
set_property IOSTANDARD LVCMOS33 [get_ports adau1761_clatchn]
set_property IOSTANDARD LVCMOS33 [get_ports adau1761_cdata]
set_property IOSTANDARD LVCMOS33 [get_ports adau1761_cout]

set_property PACKAGE_PIN AB4 [get_ports adau1761_cclk]
set_property PACKAGE_PIN AB1 [get_ports adau1761_clatchn]
set_property PACKAGE_PIN Y5 [get_ports adau1761_cdata]
set_property PACKAGE_PIN AB5 [get_ports adau1761_cout]

set_property IOSTANDARD LVCMOS33 [get_ports adau1761_mclk]
set_property PACKAGE_PIN AB2 [get_ports adau1761_mclk]
set_property IOSTANDARD LVCMOS33 [get_ports led0]
set_property PACKAGE_PIN T22 [get_ports led0]

set_property IOSTANDARD LVCMOS33 [get_ports adau1761_adc_sdata]
set_property IOSTANDARD LVCMOS33 [get_ports adau1761_dac_sdata]
set_property IOSTANDARD LVCMOS33 [get_ports adau1761_bclk]
set_property IOSTANDARD LVCMOS33 [get_ports adau1761_lrclk]
set_property PACKAGE_PIN AA7 [get_ports adau1761_adc_sdata]
set_property PACKAGE_PIN Y8 [get_ports adau1761_dac_sdata]
set_property PACKAGE_PIN AA6 [get_ports adau1761_bclk]
set_property PACKAGE_PIN Y6 [get_ports adau1761_lrclk]